FROM gradle:jdk17-alpine
ARG PRODUCTION
ARG JDBC_DATABASE_PASSWORD
ARG JDBC_DATABASE_URL
ARG JDBC_DATABASE_USERNAME

ENV PRODUCTION ${PRODUCTION}
ENV JDBC_DATABASE_URL ${JDBC_DATABASE_URL}

WORKDIR /app
RUN ls > file_list.txt
COPY file_list.txt /app
EXPOSE 8080
CMD ["java","-jar","invoicesync-0.0.1-SNAPSHOT.jar"]